Fix filename urls
logicly-au/csvlint.rb pull request #8
Opened 2021-08-12 04:27 UTC by sdt

When loading a schema that has filenames as the table urls, they get converted from a relative path to an absolute path, and then converted to a file:// url. eg. "foo.csv" might become "file:///tmp/schema/foo.csv".

Those urls get used as hash keys for the different schema tables.

Throughout the codebase there's snippets of code here and there that convert back and forth between file urls and plain file paths.

Sometimes they get it wrong.  eg. `csvlint --schema=schema.json file.csv` won't see the file, but will quietly declare that it's valid.

In order to get that to work you need `csvlint --schema=schema.json //$PWD/file.csv`. The code that converts the filename to an url is broken, and needs the extra `//` to get it to work.

This fixes the broken bits, while keeping the rest of the files working.

2021-08-13 04:03 UTC, veryrusty requested changes
Refactoring all the file URL <-> path munging into its own module is a big win!

I don't think the logic is quite right;
 * path -> url should encode 
 * url -> path shoudl decode, plus handle the cases when no hostname is provided or a hostname is present (hostname != localhost may be an error ? )

2021-08-13 04:03 UTC, veryrusty commented on lib/csvlint/file_url.rb
> +      #URI.encode(File.expand_path(path).gsub(/^\/*/, "file:///"))
I think the encode here is correct; it'd handle files with what are reserved characters in a URL, like `[` or `]`.

2021-08-13 04:03 UTC, veryrusty commented on lib/csvlint/file_url.rb
> +        File.new(uri.gsub(/^file:\/\//, ""))
This substitution isn't right for valid file URLs, and there should be a `URI.decode(...)` too.

To be fair, I had to go look up what are valid file URLs.  RFC 3986 is too long to read; wikipedia gives:
> `file:/path` (no hostname), `file:///path` (empty hostname), or `file://hostname/path`

with `file://path` not being valid (but often used).

2021-08-13 04:08 UTC, sdt commented on lib/csvlint/file_url.rb
> +        File.new(uri.gsub(/^file:\/\//, ""))
It doesn't need to handle the general case, it just needs to undo what `FileUri.url` has done.

I agree about the uri encode/decode though.

2021-08-13 04:09 UTC, sdt commented on lib/csvlint/file_url.rb
> +        File.new(uri.gsub(/^file:\/\//, ""))
Replacing the leading `file:/*` with `/` might be more robust though.

2021-08-13 04:09 UTC, sdt commented on lib/csvlint/file_url.rb
> +        File.new(uri.gsub(/^file:\/\//, ""))
ie. replace any number of slashes with just a single slash

2021-08-16 01:38 UTC, veryrusty approved these changes
Looks good!

2021-08-16 03:40 UTC, merged